package org.goldenport.cncf.context

import org.goldenport.id.UniversalId
import org.goldenport.record.Record
import org.goldenport.cncf.observability.ObservabilityEngine

/*
 * @since   Dec. 21, 2025
 *  version Dec. 31, 2025
 * @version Jan.  7, 2026
 * @author  ASAMI, Tomoharu
 */
final case class TraceId(
  underlying: UniversalId
) {
  def value: String = underlying.value
}

object TraceId {
  @deprecated(
    "UniversalId generation is core responsibility; receive UniversalId from upstream",
    "0.x.y"
  )
  def generate(): TraceId =
    throw new UnsupportedOperationException(
      "UniversalId must be generated by core UniversalIdGenerator"
    )
}

final case class SpanId(
  underlying: UniversalId
) {
  def value: String = underlying.value
}

final case class CorrelationId(
  underlying: UniversalId
) {
  def value: String = underlying.value
}

final case class ObservabilityContext(
  traceId: TraceId,
  spanId: Option[SpanId],
  correlationId: Option[CorrelationId]
) {
  def createChild(kind: ScopeKind, name: String): ObservabilityContext =
    ObservabilityContext(
      traceId = traceId,
      spanId = spanId,
      correlationId = correlationId
    )

  def emitInfo(
    scope: ScopeContext,
    name: String,
    attributes: Record
  ): Unit =
    ObservabilityEngine.emitInfo(this, scope, name, attributes)

  def emitWarn(
    scope: ScopeContext,
    name: String,
    attributes: Record
  ): Unit =
    ObservabilityEngine.emitWarn(this, scope, name, attributes)

  def emitError(
    scope: ScopeContext,
    name: String,
    attributes: Record
  ): Unit =
    ObservabilityEngine.emitError(this, scope, name, attributes)
}

object ObservabilityContext {
  @deprecated(
    "ObservabilityContext requires TraceId (UniversalId) from core; empty context is invalid",
    "0.x.y"
  )
  def empty: ObservabilityContext =
    throw new UnsupportedOperationException(
      "Provide TraceId from core UniversalIdGenerator"
    )
}
