package org.goldenport.cncf.context

import org.goldenport.id.UniversalId

/*
 * @since   Dec. 21, 2025
 * @version Dec. 31, 2025
 * @author  ASAMI, Tomoharu
 */
final case class TraceId(
  underlying: UniversalId
) extends UniversalId(underlying.value)

object TraceId {
  @deprecated(
    "UniversalId generation is core responsibility; receive UniversalId from upstream",
    "0.x.y"
  )
  def generate(): TraceId =
    throw new UnsupportedOperationException(
      "UniversalId must be generated by core UniversalIdGenerator"
    )
}

final case class SpanId(
  underlying: UniversalId
) extends UniversalId(underlying.value)

final case class CorrelationId(
  underlying: UniversalId
) extends UniversalId(underlying.value)

final case class ObservabilityContext(
  traceId: TraceId,
  spanId: Option[SpanId],
  correlationId: Option[CorrelationId]
)

object ObservabilityContext {
  @deprecated(
    "ObservabilityContext requires TraceId (UniversalId) from core; empty context is invalid",
    "0.x.y"
  )
  def empty: ObservabilityContext =
    throw new UnsupportedOperationException(
      "Provide TraceId from core UniversalIdGenerator"
    )
}
