package org.goldenport.cncf.entity.runtime

import cats.data.State
import cats.effect.Ref
import org.goldenport.Consequence
import org.goldenport.cncf.datatype.{EntityCollectionId, EntityId}
import org.goldenport.cncf.directive.{Condition, Query}
import org.goldenport.cncf.entity.{EntityPersistable, EntityPersistent, EntityQuery}
import org.goldenport.record.Record
import org.scalatest.GivenWhenThen
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

/*
 * @since   Mar. 16, 2026
 * @version Mar. 16, 2026
 * @author  ASAMI, Tomoharu
 */
final class EntityCollectionSearchConditionSpec
  extends AnyWordSpec
  with Matchers
  with GivenWhenThen {
  private val _cid = EntityCollectionId("test", "1", "person")

  "EntityCollection.search" should {
    "filter entities by generated condition object via directive.Query" in {
      Given("an entity collection with in-memory person entities")
      given EntityPersistent[PersonEntity] = new EntityPersistent[PersonEntity] {
        def id(e: PersonEntity): EntityId = e.id
        def toRecord(e: PersonEntity): Record = e.toRecord()
        def fromRecord(r: Record): Consequence[PersonEntity] =
          Consequence.failure("not used in this spec")
      }

      val p1 = PersonEntity(EntityId("m", "1", _cid), Name("taro"), Age(20))
      val p2 = PersonEntity(EntityId("m", "2", _cid), Name("hanako"), Age(30))
      val p3 = PersonEntity(EntityId("m", "3", _cid), Name("taro"), Age(40))

      val storerealm = new EntityRealm[PersonEntity](
        entityName = "person",
        loader = EntityLoader[PersonEntity](_ => None),
        state = new _SearchIdRef[EntityRealmState[PersonEntity]](EntityRealmState(Map.empty))
      )
      storerealm.put(p1)
      storerealm.put(p2)
      storerealm.put(p3)

      val descriptor = EntityDescriptor(
        collectionId = _cid,
        plan = EntityRuntimePlan(
          entityName = "person",
          memoryPolicy = EntityMemoryPolicy.StoreOnly,
          workingSet = None,
          partitionStrategy = PartitionStrategy.byOrganizationMonthUTC,
          maxPartitions = 4,
          maxEntitiesPerPartition = 16
        ),
        persistent = summon[EntityPersistent[PersonEntity]]
      )
      val collection = new EntityCollection[PersonEntity](
        descriptor = descriptor,
        storage = EntityStorage(storerealm, None)
      )

      When("searching by condition object generated by Cozy")
      val condition = domain.query.Person(
        id = Condition.any[EntityId],
        name = Condition.is(Name("taro")),
        age = Condition.any[Age]
      )
      val query = EntityQuery(_cid, Query(condition))
      val result = collection.search(query)

      Then("only matched entities are returned")
      result.map(_.data.map(_.id).toSet) shouldBe Consequence.success(Set(p1.id, p3.id))
    }

    "apply sql-like where/sort/limit/offset via Query.plan" in {
      Given("an entity collection with in-memory person entities")
      given EntityPersistent[PersonEntity] = new EntityPersistent[PersonEntity] {
        def id(e: PersonEntity): EntityId = e.id
        def toRecord(e: PersonEntity): Record = e.toRecord()
        def fromRecord(r: Record): Consequence[PersonEntity] =
          Consequence.failure("not used in this spec")
      }

      val p1 = PersonEntity(EntityId("m", "1", _cid), Name("taro"), Age(20))
      val p2 = PersonEntity(EntityId("m", "2", _cid), Name("hanako"), Age(30))
      val p3 = PersonEntity(EntityId("m", "3", _cid), Name("jiro"), Age(40))

      val storerealm = new EntityRealm[PersonEntity](
        entityName = "person",
        loader = EntityLoader[PersonEntity](_ => None),
        state = new _SearchIdRef[EntityRealmState[PersonEntity]](EntityRealmState(Map.empty))
      )
      storerealm.put(p1)
      storerealm.put(p2)
      storerealm.put(p3)

      val descriptor = EntityDescriptor(
        collectionId = _cid,
        plan = EntityRuntimePlan(
          entityName = "person",
          memoryPolicy = EntityMemoryPolicy.StoreOnly,
          workingSet = None,
          partitionStrategy = PartitionStrategy.byOrganizationMonthUTC,
          maxPartitions = 4,
          maxEntitiesPerPartition = 16
        ),
        persistent = summon[EntityPersistent[PersonEntity]]
      )
      val collection = new EntityCollection[PersonEntity](
        descriptor = descriptor,
        storage = EntityStorage(storerealm, None)
      )

      When("searching with where(age >= 20), order by age desc, offset 1, limit 1")
      val planned = Query.plan(
        condition = domain.query.Person(
          id = Condition.any[EntityId],
          name = Condition.any[Name],
          age = Condition.any[Age]
        ),
        where = Query.Gte("age.value", 20),
        sort = Vector(Query.SortKey("age.value", Query.SortDirection.Desc)),
        limit = Some(1),
        offset = Some(1)
      )
      val query = EntityQuery(_cid, planned)
      val result = collection.search(query)

      Then("the second oldest person is returned")
      result.map(_.data.map(_.id)) shouldBe Consequence.success(Vector(p2.id))
      result.map(_.totalCount) shouldBe Consequence.success(Some(3))
      result.map(r => (r.offset, r.limit, r.fetchedCount)) shouldBe Consequence.success((Some(1), Some(1), 1))
    }
  }
}

private final case class Name(value: String)
private final case class Age(value: Int)

private final case class PersonEntity(
  id: EntityId,
  name: Name,
  age: Age
) extends EntityPersistable {
  def toRecord(): Record =
    Record.dataAuto(
      "id" -> id,
      "name" -> name.value,
      "age" -> age.value
    )
}

private object domain {
  object query {
    final case class Person(
      id: Condition[EntityId],
      name: Condition[Name],
      age: Condition[Age]
    ) extends Query.ConditionShape
  }
}

private final class _SearchIdRef[A](initial: A) extends Ref[cats.Id, A] {
  private var _value: A = initial

  def get: A = synchronized {
    _value
  }

  def set(a: A): Unit = synchronized {
    _value = a
  }

  override def getAndSet(a: A): A = synchronized {
    val prev = _value
    _value = a
    prev
  }

  def access: (A, A => Boolean) = synchronized {
    val snapshot = _value
    val setter: A => Boolean = (next: A) => synchronized {
      if (_value == snapshot) {
        _value = next
        true
      } else {
        false
      }
    }
    (snapshot, setter)
  }

  override def tryUpdate(f: A => A): Boolean = synchronized {
    _value = f(_value)
    true
  }

  override def tryModify[B](f: A => (A, B)): Option[B] = synchronized {
    val (next, out) = f(_value)
    _value = next
    Some(out)
  }

  def update(f: A => A): Unit = synchronized {
    _value = f(_value)
  }

  def modify[B](f: A => (A, B)): B = synchronized {
    val (next, out) = f(_value)
    _value = next
    out
  }

  override def modifyState[B](state: State[A, B]): B = synchronized {
    val (next, out) = state.run(_value).value
    _value = next
    out
  }

  override def tryModifyState[B](state: State[A, B]): Option[B] = synchronized {
    val (next, out) = state.run(_value).value
    _value = next
    Some(out)
  }
}
